### ISSUE TITLE
"SyntaxError: invalid syntax" when running any command with "gclient"

### ISSUE THREAD

**Issue by sotrh** [cybertk/gclient#1]
I was attempting to test out the WepGPU implementation [Dawn](), but I've run into an issue. When I run `gclient sync`, python fails with a syntax error.
```
gclient sync
Traceback (most recent call last):
  File "/usr/local/bin/gclient", line 6, in <module>
    from depot_tools import gclient
  File "/usr/local/lib/python3.6/dist-packages/depot_tools/gclient.py", line 199
    print 'Overwriting Var("webkit_trunk") with %s' % new_url
                                                  ^
SyntaxError: invalid syntax
```
I installed `gclient` with the following command:
```
sudo pip3 install gclient
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gclient
  Downloading https://files.pythonhosted.org/packages/a6/63/c87ffca3801f7f48011c38ae9fc3bffca43d0a8ec58f4fe4e05458d2c35f/gclient-0.7.2.tar.gz (328kB)
    100% |████████████████████████████████| 337kB 495kB/s 
Installing collected packages: gclient
  Running setup.py install for gclient ... done
Successfully installed gclient-0.7.2
```
I'm running Linux Mint 19.1. Running `pip3 --version` gives me `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)`.

**Comment by Chaz6** [comment]
This package is seriously out of date. Someone should take it over on pypi.
